### ISSUE TITLE
Activity addition is not working

### ISSUE THREAD

**Issue by uskudarli** [idilgun/Fall2016Swe573#27]
Day is selected as 02
Month is selected as 01
Year is by default 2017

Name of activity: cycling <enter>
cycling <10mph is selected
1 hours
Add

gave "oops something went wrong, please add activity again" error

**Comment by idilgun** [comment]
@uskudarli - As with issue #26 there is a high chance this is related to issue #21 BMI page bug, if you would like to keep testing you can give another try by logging out and logging back in and I will let you know once I debug and hopefully resolve this.

**Comment by idilgun** [comment]
@uskudarli - Issue #21 has been fixed, please let me know if this issue persists.

**Comment by uskudarli** [comment]
It is persisting. I could not add again

The operations I did are: 
Name of activity: cycling 
cycling <10mph is selected
1 hours
Add

**Comment by idilgun** [comment]
@uskudarli 
Thanks for providing the details, it turns out I wasn't letting the user add the same activity twice for one day - a bad assumption. It should be fixed now.
